apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "blipapitemplate.fullname" . }}-{{ .Values.environment.stage }}
  labels:
    app: {{ template "blipapitemplate.name" . }}
    chart: {{ template "blipapitemplate.chart" . }}
    draft: {{ default "draft-app" .Values.draft }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "blipapitemplate.fullname" . }}-{{ .Values.environment.stage }}
  minReplicas: {{ .Values.autoscale.minReplicas }}
  maxReplicas: {{ .Values.autoscale.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscale.averageCPUUtilization }}