{{- if .Values.ingress.enabled -}}
{{- $fullName := include "blipapitemplate.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "blipapitemplate.fullname" . }}-{{ .Values.environment.stage }}
  labels:
    app: {{ template "blipapitemplate.name" . }}
    chart: {{ template "blipapitemplate.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.ingress.whitelist.ranges -}}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelist.ranges }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - backend:
              serviceName: {{ template "blipapitemplate.fullname" . }}-{{ .Values.environment.stage }}
              servicePort: http
  tls: 
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.hostName }}
{{- end }}